# Generated by Django 3.2.6 on 2022-01-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='請輸入主持人姓名', max_length=20)),
                ('photo', models.URLField(help_text='請輸入主持人照片連結', max_length=500)),
                ('hslist_intro', models.URLField(help_text='請輸入主持人劇本列表連結', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(help_text='請輸入劇本名稱', max_length=100)),
                ('intro', models.URLField(help_text='請輸入劇本介紹連結', max_length=500)),
            ],
        ),
    ]
