# Generated by Django 3.2.6 on 2022-02-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplelinebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script_theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(help_text='請輸入劇本名稱', max_length=100)),
                ('themename', models.CharField(help_text='請輸入劇本主題', max_length=100)),
                ('intro', models.URLField(help_text='請輸入劇本示意圖', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Script_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='請輸入劇本類型', max_length=100)),
                ('intro', models.URLField(help_text='請輸入類型示意圖', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Script',
        ),
    ]
