# Generated by Django 3.2.6 on 2022-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplelinebot', '0002_auto_20220214_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(help_text='請輸入劇本名稱', max_length=100)),
                ('theme', models.CharField(help_text='請輸入劇本題材', max_length=100)),
                ('pnumber', models.CharField(help_text='請輸入人數', max_length=100)),
                ('intro', models.URLField(help_text='請輸入劇本示意圖', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Script_pnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnumber', models.CharField(help_text='請輸入劇本人數', max_length=100)),
                ('intro', models.URLField(help_text='請輸入類型示意圖', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Script_theme',
        ),
    ]
